version:  '3.8'
services:
  swoole:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: on-failure
    user: 1000:1000
    depends_on:
      - redis
    ports:
      - 5555:9501
    environment:
      DISABLE_DEFAULT_SERVER: 1

  redis:
    image: redis
    container_name: storage
