version:  '3.8'
services:
  nginx:
    image: nginx:1.19.0-alpine
    restart: on-failure
    volumes:
      - ./app/:/usr/src/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 5555:80
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./app/:/usr/src/app
    restart: on-failure
    user: 1000:1000
    depends_on:
      - redis

  redis:
    image: redis
    container_name: storage
    expose:
      - 6379
